### PR TITLE
DynamicNotchInfo | Add text color option

### PR DESCRIPTION
**Pull request by mjn2max**
**Before:**
Screenshot 2024-10-10 at 4 33 06 PM Screenshot 2024-10-10 at 4 33 06 PM (2)

**After:**
Screenshot 2024-10-10 at 6 10 31 PM (2) Screenshot 2024-10-10 at 6 10 31 PM

**Usage:**
```swift
let notch = DynamicNotchInfo(
    icon: Image(systemName: "figure"),
    title: "Figure",
    description: "Looks like a person",
    iconColor: .green,
    textColor: .green
)
notch.show(for: 3)
```

### CODE REVIEW

**Comment by MrKai77** [comment]
Would you be able to resolve the merge conflicts? Thanks :)

**Comment by mjn2max** [comment]
> Would you be able to resolve the merge conflicts? Thanks :)

Updated

**Comment by MrKai77** [comment]
Just tested it, looks great! Thank you so much, and sorry for the long wait 😅

**Comment by mjn2max** [comment]
> Just tested it, looks great! Thank you so much, and sorry for the long wait 😅

Glad to be part of such an amazing project! 😁

**Pull request merged**
